filters: [
    "(?i)\b(n[ i1l! ][ g9q ]+[ g9q ][ e3r ]*)\b",
    "(?i)\b(n[ i1l! ][ g9q ]+[ a@ ])\b",
    "(?i)\b(f[ a@ ][ g9q ]+[ g9q ][ o0 ]t)\b",
    "(?i)\b(f[ a@ ][ g9q ]+)\b",
    "(?i)\b(c[ hx ][ i1l! ][ n ]+[ kq ])\b",
    "(?i)\b(s[ p ]+[ i1l! ][ c ]+[ kq ])\b",
    "(?i)\b(b[ e3a@ ][ a@ ][ n ]+[ e3r ]*)\b",
    "(?i)\b(a[ b8 ][ o0 ]+)\b",
    "(?i)\b(a[ b8 ][ b8 ][ o0 ]+)\b",
]